#+TITLE: RaiseNow Forms for BOS Schweiz

To adjust the config please edit =raisenow.yml=.

Warning: Changes will affect live forms immediately!

Results will be available here:

  https://www.bos-schweiz.ch/raisenow-forms/index.html

- [[https://docs.google.com/spreadsheets/d/1RVfQuZ9nlwN20ZRR1_Ljg5AlZ5UqXJfkr2XcQcovAq4/edit#gid=0][Project management sheet]]
- [[https://docs.google.com/spreadsheets/d/19wcZ4YVDDE_n4ruTJVbk1vI3ifyzM2Hl2cisSnTB-c0/edit#gid=0][Form overview]]

* Overview

This repo holds the configuration and setup for RaiseNow forms used by
BOS Schweiz. The configuration is maintained in YAML. Compared to
JSON, YAML is easier to read and edit, more powerful (e.g. merge
keys), and can include comments, and thus can easily be documented
inline.

In addition to the standard feature set of YAML, the build script support deep merge via =<<<:= and multiple ordered deep merges via =<<<1:=, =<<<2:=, etc.

There is a Makefile to build the project to =public= and deploy the
project to bos-schweiz.ch hosting on AWS (provided by seven49). CI is
set up, so pushes to the master branch will trigger a deploy
automatically. Deployment takes approx. 20 seconds.

* References

- [[https://manage.raisenow.com][RaiseNow Management Interface]]
- [[https://support.raisenow.com/hc/en-us/articles/360001586658-Integrate-the-Widget-into-your-Page][Integrate the Widget into your Page]]
- [[https://support.raisenow.com/hc/de/articles/360011968358-Anpassen-der-Konfiguration-Sprache-und-Bedingungen][Anpassen der Konfiguration Sprache und Bedingungen]]
- [[https://support.raisenow.com/hc/en-us/articles/360011964278-Implement-Custom-Event-Handlers][Implement Custom Event Handlers]]
- [[https://github.com/DimitarChristoff/epik][epik]]
