name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build
      run: make
    - name: Update host key
      run: ssh-keyscan 185.125.27.16 >> ~/.ssh/known_hosts
    - name: Deploy
      run: make deploy
